version: "3"

services:

  generate-user:
    tty: true
    stdin_open: true
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
    image: ghcr.io/jinyoung/gpt-engineer:v5
#    command: ["-sh"]
    volumes:
      - ../user:/project
  generate-driver:
    tty: true
    stdin_open: true
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
    image: ghcr.io/jinyoung/gpt-engineer:v5
#    command: ["-sh"]
    volumes:
      - ../driver:/project
  generate-vehicle:
    tty: true
    stdin_open: true
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
    image: ghcr.io/jinyoung/gpt-engineer:v5
#    command: ["-sh"]
    volumes:
      - ../vehicle:/project
